// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(knwlInstance) {
    this.calls = function() {
      var clean, i, len, regEx, res, websites, word, words;
      words = knwlInstance.words.get('linkWords');
      clean = function(word) {
        return word.replace(/[\(\)!]/g, "");
      };
      regEx = /(^(www)?\.)?([\w-])*(\.([\w]){2,10})$/;
      websites = [];
      for (i = 0, len = words.length; i < len; i++) {
        word = words[i];
        res = clean(word).match(regEx);
        if (res != null) {
          websites.push(res[0]);
        }
      }
      return websites;
    };
  };

}).call(this);
